#ifndef AVT_VMBAPI_VERSION_H
#define AVT_VMBAPI_VERSION_H

#define VIMBACPP_VERSION_MAJOR  1
#define VIMBACPP_VERSION_MINOR  3
#define VIMBACPP_VERSION_PATCH  0

#endif //AVT_VMBAPI_VERSION_H
