#ifndef AVT_VMBAPI_VERSION_H
#define AVT_VMBAPI_VERSION_H

#define VIMBACPP_VERSION_MAJOR  1
#define VIMBACPP_VERSION_MINOR  4
#define VIMBACPP_VERSION_PATCH  1

#endif //AVT_VMBAPI_VERSION_H
